### ISSUE TITLE
Provide dist with bundled deps

### ISSUE THREAD

**Issue by rolyatmax** [tsherif/pico-mercator#4]
I'm loving this library! I want to start `npm install`ing in my projects already. Since this library seems to depend on `gl-vec4` and `gl-mat4`, it might be a good idea to stick those in the `package.json` `dependencies` (or just `gl-matrix` and tree-shake the rest), and provide some bundled versions of the library?

Was this something you were already thinking about? It looks like Pico uses webpack, but if you were wanting something a bit smaller, [rollup](https://github.com/rollup/rollup) is a nice option. I've used it on a few projects (including my [spring-animator](https://github.com/rolyatmax/spring-animator/blob/master/rollup.config.js) library). If we can decide on what types of modules to export (UMD, CommonJS, ES6 modules, etc) and a bundler to use, I'd be happy to open a PR that takes a stab at setting it up.

**Comment by tsherif** [comment]
Definitely want to do this and am very tempted to take you up on your offer, but I really should get some practice with webpack...

**Comment by rolyatmax** [comment]
Ohhhh - I'm seeing a webpack config already. (Honestly glad you didn't take me up on this offer, hahahaha)
